// Ported from upstream Sources/Pulse/Usage/SpendAgent.swift.
//! A coding agent that leaves a record of its work on this machine.
//!
//! Not a `Provider`, deliberately: a provider is something Pulse can draw a ring for; an agent is
//! something that has spent tokens here. The two lists overlap and are not the same.
//!
//! The enum itself is generated by the registry in [`super::sources`]: adding an agent is one
//! file there and one line in `registry!`, and every method below follows the source's answers.
//!
//! TODO(spend): upstream's catalogue has 54 sources. Seventeen are ported (Claude Code, Codex,
//! OpenCode, Kilo CLI, Grok Build, Kimi CLI, Devin, and Group A: Pi, Oh My Pi, OmO Native, Kimchi,
//! Prime Agent, Gemini CLI, Qwen Code, Amp, Droid, OpenClaw). Still to do, by upstream group:
//! - B (editor logs): Roo Code, Kilo Code, Cline, CodeBuddy, WorkBuddy, Cherry Studio,
//!   Command Code, OpenCodeReview, ZCode
//! - C (databases): Hermes, Goose, Zed, Kiro, Crush, Unsloth, Antigravity CLI/IDE, MiMo Code,
//!   Devin Desktop
//! - D (structured logs): Mux, Codebuff, Freebuff, JCode, Augment, Gajae Code, Junie, DeepSeek
//!   Harness, FX, LM Studio, Reasonix
//! - E (exports): Cursor, Antigravity (export), Trae, Warp, Hindsight, MiniMax Code
//! - F: GitHub Copilot

use serde::de::{Error, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

pub use super::sources::SpendAgent;
use super::transcripts::Sources;
use crate::provider::Provider;

impl SpendAgent {
    /// The persisted id (`claudeCode`, `openCode`, `kiloCLI`...): what is serialized and what
    /// the cache files are named by.
    pub fn raw(self) -> &'static str {
        self.source().raw()
    }

    pub fn from_raw(raw: &str) -> Option<SpendAgent> {
        SpendAgent::ALL.iter().copied().find(|agent| agent.raw() == raw)
    }

    /// The canonical id upstream's catalogue gives it.
    pub fn source_id(self) -> &'static str {
        self.source().source_id()
    }

    /// Product names, left untranslated.
    pub fn display_name(self) -> &'static str {
        self.source().display_name()
    }

    /// The provider whose transcripts this agent is read from, for Claude Code and Codex: the
    /// two histories `read_ledger` and the per-provider history card read. None for every other
    /// agent, which is read here and nowhere else.
    pub fn provider(self) -> Option<Provider> {
        self.source().transcript_provider()
    }

    pub fn from_provider(provider: Provider) -> Option<SpendAgent> {
        SpendAgent::ALL.iter().copied().find(|agent| agent.provider() == Some(provider))
    }

    /// The provider whose detailed card shows this agent's spend (upstream `iconProvider`).
    pub fn card_provider(self) -> Option<Provider> {
        self.source().card_provider().or_else(|| self.provider())
    }

    /// The agents whose spend a provider's detailed card shows when the provider keeps no
    /// transcripts of its own: every agent that borrows its name (upstream `cardHistory`).
    pub fn for_card(provider: Provider) -> Vec<SpendAgent> {
        SpendAgent::ALL.iter().copied().filter(|a| a.provider().is_none() && a.card_provider() == Some(provider)).collect()
    }

    /// The file stem of the agent's mark in `assets/icons`, where the set has one.
    pub fn icon_resource(self) -> Option<&'static str> {
        self.source().icon().or_else(|| self.provider().map(Provider::icon_resource))
    }

    /// The models.dev plan vendor an agent's models fall back to when no first-party provider
    /// publishes them.
    pub fn price_vendor(self) -> Option<&'static str> {
        self.source().price_vendor()
    }

    /// Every file or folder the agent is read from, whether or not it exists.
    pub fn inputs(self, sources: &Sources) -> Vec<std::path::PathBuf> {
        self.source().inputs(sources)
    }

    /// Whether this agent has left a store on this machine: installed, or at least used once. An
    /// agent that is absent entirely is not named anywhere in the pane.
    pub fn is_present(self, sources: &Sources) -> bool {
        self.inputs(sources).iter().any(|path| path.exists())
    }

    /// Whether the store records the prompt cache at all.
    pub fn reports_cache_reads(self) -> bool {
        self.source().reports_cache_reads()
    }

    /// Whether the store is an export or capture rather than a native log.
    pub fn requires_usage_export(self) -> bool {
        self.source().requires_usage_export()
    }

    /// Read off a real machine with real work in it upstream.
    pub fn has_captured_validation(self) -> bool {
        self.source().has_captured_validation()
    }
}

impl Serialize for SpendAgent {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.raw())
    }
}

impl<'de> Deserialize<'de> for SpendAgent {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct Raw;
        impl Visitor<'_> for Raw {
            type Value = SpendAgent;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("the id of a token spend agent")
            }
            fn visit_str<E: Error>(self, value: &str) -> Result<SpendAgent, E> {
                SpendAgent::from_raw(value).ok_or_else(|| E::custom(format!("unknown spend agent {value:?}")))
            }
        }
        deserializer.deserialize_str(Raw)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_registered_agent_has_a_unique_id_and_round_trips_through_serde() {
        let mut raws: Vec<&str> = SpendAgent::ALL.iter().map(|a| a.raw()).collect();
        let mut ids: Vec<&str> = SpendAgent::ALL.iter().map(|a| a.source_id()).collect();
        raws.sort();
        ids.sort();
        raws.dedup();
        ids.dedup();
        assert_eq!(raws.len(), SpendAgent::ALL.len(), "two agents share a persisted id");
        assert_eq!(ids.len(), SpendAgent::ALL.len(), "two agents share a source id");
        for agent in SpendAgent::ALL {
            let json = serde_json::to_string(agent).unwrap();
            assert_eq!(json, format!("\"{}\"", agent.raw()));
            assert_eq!(serde_json::from_str::<SpendAgent>(&json).unwrap(), *agent);
            assert!(!agent.display_name().is_empty());
        }
        assert!(serde_json::from_str::<SpendAgent>("\"nobody\"").is_err());
    }

    #[test]
    fn the_seven_legacy_agents_keep_the_ids_they_were_persisted_with() {
        // The registry lists the seven first, in their order; the readers added after them are checked elsewhere.
        let legacy = &SpendAgent::ALL[..7];
        let raws: Vec<&str> = legacy.iter().map(|a| a.raw()).collect();
        assert_eq!(raws, ["claudeCode", "codex", "openCode", "kiloCLI", "grok", "kimiCLI", "devinCLI"]);
        let ids: Vec<&str> = legacy.iter().map(|a| a.source_id()).collect();
        assert_eq!(ids, ["claude", "codex", "opencode", "kilo", "grok", "kimi", "devin-cli"]);
    }

    #[test]
    fn a_card_shows_the_agents_that_borrow_its_provider_and_the_transcript_two_keep_their_own() {
        assert_eq!(SpendAgent::for_card(Provider::OpenCodeGo), [SpendAgent::OpenCode]);
        assert_eq!(SpendAgent::for_card(Provider::KimiCode), [SpendAgent::KimiCli]);
        assert_eq!(SpendAgent::for_card(Provider::Grok), [SpendAgent::Grok]);
        // Claude Code and Codex are read as transcripts, not as card agents.
        assert!(SpendAgent::for_card(Provider::ClaudeCode).is_empty());
        assert_eq!(SpendAgent::from_provider(Provider::Codex), Some(SpendAgent::Codex));
        assert_eq!(SpendAgent::from_provider(Provider::Grok), None);
        assert_eq!(SpendAgent::KiloCli.card_provider(), None);
    }

    #[test]
    fn plan_vendors_follow_upstream() {
        assert_eq!(SpendAgent::ClaudeCode.price_vendor(), None);
        assert_eq!(SpendAgent::Codex.price_vendor(), None);
        assert_eq!(SpendAgent::OpenCode.price_vendor(), Some("opencode-go"));
        assert_eq!(SpendAgent::KiloCli.price_vendor(), Some("kilo"));
    }

    #[test]
    fn an_agent_is_present_only_when_one_of_its_stores_exists() {
        let root = tempfile::tempdir().unwrap();
        let sources = Sources::new(root.path());
        assert!(SpendAgent::ALL.iter().all(|a| !a.is_present(&sources)));
        std::fs::create_dir_all(root.path().join(".grok").join("sessions")).unwrap();
        std::fs::create_dir_all(root.path().join(".claude").join("projects")).unwrap();
        let present: Vec<SpendAgent> = SpendAgent::ALL.iter().copied().filter(|a| a.is_present(&sources)).collect();
        assert_eq!(present, [SpendAgent::ClaudeCode, SpendAgent::Grok]);
    }
}
